# Fasi del lavoro {#lavoro}

<br>

## Primi prototipi {#prototipi}

Dopola visione del [video sopracitato](https://www.youtube.com/watch?v=r6sGWTCMz2k) nel mese di luglio 2019, ho realizzato il primo prototipo dell'animazione principale in _Javascript_ seguendo [alcuni tutorial](https://www.youtube.com/watch?v=MY4luNgGfms) di [_The Coding Train_](https://www.youtube.com/thecodingtrain). A dicembre dello stesso anno ho poi riscritto il precedente prototipo in _Java_ e ne ho ampliato le funzionalità. Ciò mi ha permesso di familiarizzare con i vari algoritmi impiegati nella generazione delle informazioni utili alla visualizzazione dell'animazione e la loro implementazione.

<br>

## Ricerca teorica {#ricerca}

Già nel mese di dicembre 2019 mi ero approcciato allo studio della trasformata di Fourier e di una sua applicazione alla compressione delle immagini con il metodo JPEG _lossy_ - basato sulla trasformata discreta del coseno - con lo scopo di produrre un trittico di poster sull'argomento, parte della prova di esame del corso di _Analisi Matematica 3_.

La fase di ricerca teorica vera e propria ha avuto inizio nel mese di marzo 2020 e, su indicazione del mio relatore Prof. Paolo Boggiatto, ha riguardato principalmente lo studio approfondito di alcune sezioni del libro _**Fourier Analysis and Applications**_ di C. Gasquet e P. Witomski: nello specifico, il capitolo II - _i segnali periodici e la serie di Fourier_ -, la lezione 8 del capitolo III - _la trasformata discreta di Fourier_ - e le lezioni 17, 18 e 19 del capitolo VI - _la trasformata di Fourier di funzioni integrabili, la trasformata inversa e lo spazio $\mathcal{S}(\mathbb{R})$_.

La questione centrale della tesi, alla base del funzionamento dell'animazione, riguarda la possibilità di scrivere una funzione $f: \mathbb{R} \longrightarrow \mathbb{C}$ periodica di periodo $a$ come
$$f(t)=\sum_{n=-\infty}^{+\infty}c_{n}e^{2\pi in \frac{t}{a}} \ ,$$
dove $c_n \in \mathbb{C}$ e $n \in \mathbb{Z}$, sotto _minime ipotesi_ sulla funzione $f$.

Inoltre, durante lo sviluppo del software, si è rivelato utile affrontare il tema delle curve di Bèzier, in particolare delle _polybézier_ - ovvero di una curva di Bèzier continua definita a tratti. Per potenziare le mie conoscenze in materia, ho fatto uso del libro _A Primer on Bézier Curves_, [disponibile online](https://pomax.github.io/bezierinfo/), che mi ha fornito le basi necessarie per manipolare tali oggetti da un punto di vista informatico.

Prima della fase di programmazione si è poi resa necessaria una ricerca degli strumenti informatici più adatti. Una discussione degli strumenti adottati e del loro impiego è consultabile al capitolo dedicato...

<br>

## Animazioni {#animazioni}

Terminata la raccolta e lo studio delle informazioni necessarie, ha potuto avere inizio la programmazione delle animazioni in maniera più accurata rispetto ai [primi prototipi](#prototipi).
Il loro sviluppo è avvenuto in _JavaScript_, facendo ampio uso delle librerie _open source_ [_p5.js_](https://p5js.org/), per il _creative coding_, e _complex.js_, per la gestione dei numeri complessi. Ciò ha permesso, a differenza di un video, di rendere le animazioni **interattive**, andando così a potenziare il legame con lo spettatore che si trasforma quindi in utente attivo.

L'obiettivo delle animazioni è quello di agevolare la comprensione dei concetti teorici tramite una loro **visualizzazione immediata** e metterne in evidenza le sfaccettature più nascoste, andando ad affiancare ed assistere l'ingegno e le capacità immaginative dei loro fruitori.

Molta attenzione è stata riposta nella loro **estetica**, dacché ritengo che l'aspetto artistico non sia affatto secondario al contenuto, ma piuttosto funzionale a quest'ultimo, poiché in grado di avvicinare e coinvolgere lo spettatore-utente instaurando una connessione emotiva e sensoriale più forte.<br>
La filosofia alla base di questo approccio deriva sicuramente dalla visione artistica del [video originale](https://www.youtube.com/watch?v=r6sGWTCMz2k). Tuttavia, è stata ampiamente influenzata anche dagli _Elementi_ di Euclide a colori, ovvero un'edizione del celebre libro di geometria in cui simboli e figure colorate sostituiscono le lettere, e dal pensiero del suo autore, Oliver Byrne, che ho avuto modo di apprezzare durante il corso di _Storia della Matematica Antica e Moderna_.<br>

Ho infine curato l'**accessibilità**, ovvero la facilità di utilizzo, e la **portabilità**, cioè la corretta visualizzazione e fruizione su diversi tipi di dispositivi, principi chiavi per garantire all'utente un'esperienza fluida e priva di ostacoli o barriere di carattere tecnico.

<br>

## Presentazione {#presentazione}

La presentazione è stata realizzata con [_**Reveal.js**_](https://revealjs.com/), un framework _open source_ per presentazioni HTML a cui ho apportato diverse personalizzazioni.<br>
Ciò mi ha permesso di **integrare perfettamente** (ovvero _seamlessly_ in inglese) le **animazioni** nell'ambiente della presentazione, senza richiedere all'utente operazioni aggiuntive. Inoltre, il file HTML può essere visualizzato da un'ampia gamma di dispositivi tramite un qualsiasi _browser_ e le ridotte dimensioni del file lo rendono ideale per la distribuzione online.

#### {-#filosofia}
La filosofia che mi ha guidato nella creazione delle slide è la stessa discussa nel [precedente paragrafo](#animazioni): accessibilità e piacevolezza estetica hanno costituito il fondamento su cui sviluppare il contenuto e il mezzo con cui esaltarlo, ma senza in alcun modo prevaricarlo. In tal senso, [diversi accorgimenti](#features) sono stati adottati per affinare l'esperienza dell'utente finale.

#### {-}

Nel [capitolo successivo](#commento) verrà fornito un commento di carattere teorico alla presentazione.


